### PR TITLE
You can localize this lua function here

### PR DESCRIPTION
**Pull request by Developaws**
Teeny tiny optimization, makes lua a happy bunny.

### CODE REVIEW

**Comment by funkydude** [comment]
Why are you reading the code of this addon a mere 4 hours after you start updating a competitor?

This addon is licensed under All Rights Reserved and I do not appreciate my hours of work on it being used as the baseline to speed up the development of a competitor.

That's not to mention that fact there's literally 0 reason for a competitor to exist. You split the userbase and development effort in half for what benefit exactly? If there's an issue with Capping, open an issue ticket or submit a PR?

**Comment by Developaws** [comment]
Fine. If you don't want the help.

**Comment by funkydude** [comment]
My entire reply is literally saying "instead of creating pointless fragmentation, come help" ??

**Comment by Developaws** [comment]
And my entire point is as followed.

a) Your copyright means nothing, you don't own Lua, nor the WoW API. There's a limited set way of doing things, thus I'm not "stealing" your code, nor any of the concepts on which they're build on.
b) Last I checked, competition in businesses was good. But I mean, if you're that concerened and greedy about it, you don't really deserve the help.
c) Frankly, at the end of the day, the DBM-PvP system was there before, and just needed love, so really the splitting of the userbase was created by yourself, when you could have helped to contribute to a pre-existing project. Personally, I see no harm in contributing to two projects who have like minded approaches, and go about doing it COMPLETELY seperately.

But, I do wish you the best of regards with your project, and hope you get the support you require without you attacking the people :)

Regards,
Krystals.

**Comment by funkydude** [comment]
> a) Your copyright means nothing, you don't own Lua, nor the WoW API. There's a limited set way of doing things, thus I'm not "stealing" your code, nor any of the concepts on which they're build on.

My "copyright" i.e. "All Rights Reserved" is down to my hours of work grinding and testing battlegrounds, etc, not the Lua API. I did not do that work for you to just reference "oh, that's what the widget id is, I'll just copy it instead of putting in the work myself to find out what it is"

That is, **without even asking** if that was okay to do so. I mean, that's not even copyright, **that's just being polite**.

Ultimately, we can ask CurseForge what they think about author copyright.

> b) Last I checked, competition in businesses was good. But I mean, if you're that concerened and greedy about it, you don't really deserve the help.

Seriously? This isn't a business, this is free WoW addons done in our spare time. Fragmentation is not good, especially not when it comes to these sorts of projects.

> c) Frankly, at the end of the day, the DBM-PvP system was there before, and just needed love, so really the splitting of the userbase was created by yourself, when you could have helped to contribute to a pre-existing project.

Capping has been around longer than DBM-PvP (since WoW 3.1), DBM-PvP has been around since WoW 5.3.
Perhaps you are a recent player, but you can look this up by looking at old zips on curseforge.

So no, I did not split the community, DBM authors chose to do that.

> Personally, I see no harm in contributing to two projects who have like minded approaches, and go about doing it COMPLETELY seperately.

I asked you before, but why? What is the underlying motivation to bother with doing this? The only thing I can think of is the bar anchor, which I have already stated is doable as a feature in Capping.

> But, I do wish you the best of regards with your project, and hope you get the support you require without you attacking the people :)

I was not "attacking" you, I was asking why you "coincidentally" started looking at my code 4 hours after a commit on a competitor.

**Comment by Developaws** [comment]
Okay, Firstly.. I wasn't looking at your code 4 hours after working on a competitor, I'd been working on this "competitor" longer, kfnx.

Secondly, I'm not stealing your hard work, taking all these ID's you work so hard for, you could try actually checking achievements and see I've been manually data mining them myself since earliest 29th. [As seen here](https://worldofwarcraft.com/en-gb/character/eu/terokkar/developaws/achievements/player-vs-player/battle-for-gilneas)

**Pull request closed without merging**
