### PR TITLE
Add Narduke and Anenga to Ashran

### PR DESCRIPTION
**Pull request by hewozuoai**
Add Narduke and Anenga to ashran.

### CODE REVIEW

**Comment by funkydude** [comment]
You haven't explained anything in your PR. For example, why should these even be added?

**Comment by hewozuoai** [comment]
These NPCs allow turn in of fragments to summon elites.

It would be really helpful having them as a bar to see if yours and your enemies is alive to plan you attack or defense.

For example if you have just cleared RoC and are planning to turn in but don't know your guys is dead then its a wasted journey back to base where you could be farming other things (forest flowers, rares etc). It would also help your team to know when the enemy turn in guy is up so you can organize a group to go murder him before they get a chance to summon their elite.

**Comment by funkydude** [comment]
> but don't know your guys is dead then its a wasted journey

This feature isn't a status indicator of if an NPC is alive or dead because the bar disappears after ~20 seconds. So if you missed it, then you wouldn't know that the NPC died and this feature doesn't change that.

> It would also help your team to know when the enemy turn in guy is up

This feature doesn't give you warnings when an NPC respawns, it's a health indicator, and it doesn't show when the NPC is at 100.

I did this BG the other day and it was just a rush to the boss and nuke, no one cared about grinding for hand-ins anymore. So I'm struggling to see why the hand-in NPCs are really that important that we should track their HP? I feel like they are in the same boat as Alterac Valley hand-in NPCs.

**Comment by funkydude** [comment]
No response, closing.

**Pull request closed without merging**
